# GITLAB + JENKINS + SONARQUBE + TRIVY — 100% HORS LIGNE

services:

  gitlab:
    image: gitlab-ce:local
    container_name: gitlab
    hostname: gitlab.local
    ports:
      - "80:80"
      - "443:443"
      - "2222:22"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    shm_size: '256m'
    restart: unless-stopped

  registry:
    image: registry:2
    container_name: registry
    ports:
      - "5000:5000"
    volumes:
      - registry-data:/var/lib/registry
    restart: unless-stopped

  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonar-db:5432/sonarqube
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-extensions:/opt/sonarqube/extensions
      - sonarqube-logs:/opt/sonarqube/logs
    depends_on:
      - sonar-db
    restart: unless-stopped

  sonar-db:
    image: postgres:15-alpine
    container_name: sonar-db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonarqube
    volumes:
      - sonar-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/mac/docker:/usr/local/bin/docker
      - /Users/mac/docker-compose:/usr/local/bin/docker-compose
      - /Users/mac/trivy:/usr/local/bin/trivy
    user: root
    depends_on:
      - gitlab
      - registry
      - sonarqube
    restart: unless-stopped

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  jenkins_home:
    external: true
  registry-data:
  sonarqube-data:
  sonarqube-extensions:
  sonarqube-logs:
  sonar-db-data:
